### ISSUE TITLE
Processing.py does not play nicely with flake8 etc.

### ISSUE THREAD

**Issue by whonut** [jdf/processing.py#157]
I use flake8, a linter and PEP8 compliance checker on my code regularly. I've been using Processing outside of the Development Environment and unfortunately flake8 throws a bunch of 'Undefined name' errors. It also complains about lack of whitespace where it usually wouldn't, among other things. I assume this is because Processing-specfic functions and variables aren't brought in via an import so the linter knows nothing about them. In any case, it's very annoying.

I don't know whether anything can be done about this becaubut I thought I'd bring it to your attention.

**Comment by tildebyte** [comment]
I don't know your environment, but until recently[1] I'd been using Sublime Text 3 along with the P5.py standalone (i.e. running without the PDE). I had to compile a list of P5 keywords to stick into the exception list for one of the Python linters, so that might be a place to start.
I can tell you that a solution inside of P5.py itself is a long shot; the mode (for the PDE) is usually the priority, and all the more so with the development effort for Processing 3 compatibility just getting under way.

[1] Working on switching to Atom :+1:

**Comment by riverfr0zen** [comment]
For what it's worth, if you are using SublimePythonIDE with SublimeText3, you can add a list of exceptions in either the plugin's User settings or Project settings:

In User settings, add:

`    "pyflakes_ignore": ["background", "ellipse", "fill", "size" ... ]`

In Project settings, add to 'settings' object:
```
    "settings": {
	    // Ignoring for Processing.py projects
	    "pyflakes_ignore": ["background",
	                        "ellipse",
	                        "fill",
	                        "size"]
    }

```
