### ISSUE TITLE
pyde file double-click and drag-n-drop support 

### ISSUE THREAD

**Issue by jeremydouglass** [jdf/processing.py#284]
I have noticed that Processing PDE (3.3.6) is not associated with .pyde files -- double-clicking them on macOS 10.12.6 does nothing, and explicitly dragging them onto the PDE icon does nothing (they snap back without launching).

By contrast, .pde (Java) files can be double-clicked to launch and can be drag-and-dropped onto the PDE app to launch.

Is better default pyde launch support something that could be defined as part of a mode, or does it need to be altered at the main Processing application level regardless of whether the mode is installed or not?

A workaround is that double-click application associations can be manually configured by each user -- although drag-and-drop cannot be.

**Comment by jdf** [comment]
I'd guess that it has to be baked into Processing itself; @benfry, who's most knowledgeable about this sort of thing in the PDE?

**Comment by benfry** [comment]
Just me… It's tricky because it's handled differently across each platform. On Windows it's a registry key that we add via JNA (see the Platform classes). On the Mac, it's a change to the `Info.plist` file inside `Processing.app`. 

Since we don't have dozens of Modes, it may just be something where we add `.pyde` as one of the defaults that we support.

**Comment by jdf** [comment]
That would be excellent. Let me know if I can be of service.

**Comment by jdf** [comment]
Thanks, Ben!
