### ISSUE TITLE
exit() doesn't

### ISSUE THREAD

**Issue by jdf** [jdf/processing.py#286]
`exit()` should raise an exception so that it terminates the sketch right away.

Thanks @jeremydouglass for pointing this out.

**Comment by geekRishabhjain** [comment]
Not able to get, what it means? exit() is working fine in my system

**Comment by jeremydouglass** [comment]
I think it might be related to this?

https://github.com/jdf/processing.py/issues/264#issuecomment-346830532

So if I'm reading that thread right then this issue might have been resolved, specifically by build 3034. If so, this could be closed. The only odd thing is that this issue was opened a week after that thread, so maybe it is a separate aspect of the problem.

**Comment by jeremydouglass** [comment]
Actually, come to think of it, I believe this relates to the fact that exit() sets up the sketch for exit after the current draw() frame terminates -- it doesn't actually exit. See for example:

https://forum.processing.org/two/discussion/25974/terminate-execution-and-close-window

So if you write this:

```
def draw():
    val=0
    for x in range(0,10):
        if x==1:
            exit()
        print(x)
```

...you might expect the sketch to print "0", call exit, and exit. But it doesn't. It prints 0 1 2 3 4 5 6 7 8 9, falls out the bottom of draw, and *then* exits.

**Comment by jdf** [comment]
Yeah... I'll get to this as soon as I can. It's annoying.

**Comment by jdf** [comment]
Actually, this is as designed in Processing.

https://py.processing.org/reference/exit.html

I don't like it, but the goal os for Python Mode's behavior to match Java Mode.
