### ISSUE TITLE
if use fill in class definition will get a NullPointerExceptionat错误

### ISSUE THREAD

**Issue by yonghuming** [jdf/processing.py#307]
```
class Ball():
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.vy = random(-1,0)
        self.ay = random(0.1, 0.2)
        # self.c = c
        self.c = random(255)
        fill(255)
        
        self.radius = random(10, 50)
        # fill(random(255))
        
    def run(self):
        self.update()
        self.display()
        
    def update(self):
        self.vy += self.ay
        self.y += self.vy
        
    def display(self):        
        
        # ellipse(self.x, self.y, 20, 20)
        ellipse(self.x, self.y, self.radius, self.radius)
        
        
        
balls = []
ball = Ball(100, 20)
def setup():
    size(800, 600)
    noStroke()
    
def draw():
    global ball, balls
    background(0)
    # ball.run()
    ball = Ball(mouseX, mouseY)
    balls.append(ball)
    # fill(random(255))
    for ball in balls:
        ball.run()
    
    
```
![image](https://user-images.githubusercontent.com/435079/45298786-20566c00-b53c-11e8-86dc-916ebb438066.png)
what a terrible exprience programming processing in python, meaningless error msg

**Comment by yonghuming** [comment]
i found why ,should not init Ball before setup

**Comment by jdf** [comment]
> what a terrible exprience programming processing in python, meaningless error msg

It's difficult to anticipate every possible user error, and to write code that will interpret the resulting crash in a way that will make clear to the user where their error is.

For eample, if you make the same mistake in Java mode

```java
public class C {
  public C() {
    fill(255);
  }
}

C c = new C();

void setup() {
  size(300, 300);
}

void draw() {
}
```

The resulting error message is 

![err](https://user-images.githubusercontent.com/55948/45301712-7b0daa80-b4df-11e8-9424-7f0492594e60.png)

In your case, the problem is not that you construct a Ball before `setup`, but that you call `fill()` before `setup`. Perhaps you could file a bug on the Processing project, suggesting that calling `fill` before setup could have a more friendly error message?
