### ISSUE TITLE
How can I update the processing.py docs? 

### ISSUE THREAD

**Issue by L4ZZA** [jdf/processing.py#316]
Hi Jonathan,

I'm in the middle of a processing project using python and I'm struggling using PVectors because the documentation is missing from the official page. I'm willing to update it but I'm running in two issues:
First of all I can't seem to find the repository for the [py.processing.org](url) website and second I can't recognize where are the main classes implemented in the code repository.

If you could let me know this two things I'll be able to read and extract the information needed to update the reference page.

Thanks,
Pietro

**Comment by villares** [comment]
You might want to try looking the same PVector methods of Java Mode listed here:  https://processing.org/reference/PVector.html

And there is some Pythonic sugar with operator overloading going on so you can add PVectors with `+` :)

Í think the documentation repo is this https://github.com/kazimuth/processing-py-site but I have a bad feeling about it, because there is this merged patch that is still wrong on the live site: https://github.com/kazimuth/processing-py-site/pull/115 I wish @kazimuth could have a look.

**Comment by villares** [comment]
Hi @jdf, would you have a way of asking @kazimuth to update the live site with the fix?

**Comment by villares** [comment]
Not yet live at https://py.processing.org/tutorials/interactivity/

**Comment by jdf** [comment]
Ok, try now.

**Comment by villares** [comment]
Wonderful!
