### ISSUE TITLE
Would it be possible to remove Jython dependency to support Python 3?

### ISSUE THREAD

**Issue by berinhard** [jdf/processing.py#348]
Hi @jdf, first of all, thanks for your work on maintaining Processing's Python Mode! I was introduced to Processing by it and, so far, it's being a joyful journey.

One thing I noticed is that there are some projects to use Python3 with creative coding and I even wrote myself one of them called [pyp5js](https://github.com/berinhard/pyp5js). I know these projects are being created because Jython doesn't have any roadmap to support Python 3, thus, processing.py remains stuck with Python 2. Although these py3 ports provide the benefit of using Python 3, they have with a huge downside IMHO which is losing compatibility with all the other Processing libraries, such as `processing.pdf` or `processing.svg`.

Recently, I've discovered 2 other alternatives to integrate Python 3 with Java:

- [py4j](https://www.py4j.org/)
- [graalpython](https://github.com/graalvm/graalpython)

Do you think it would be possible to replace Jython by one of these solutions? Is there a possible minimum prototype to study the viability of doing so? Let me know how I could help with this because I'm very interested and willing to help on moving processing.py to Python 3 :+1:

**Comment by jdf** [comment]
The purpose of my project was to make it possible to do Processing programming with Python *syntax*, not to integrate Processing with Python. 

While I imagine it's possible to do as you suggest, it would take a fantastic amount of work, and I won't be the one to do it.

Having said that, I'll 100% support the project that comes along to replace my Python Mode!

**Comment by berinhard** [comment]
Hi @mpsftw thanks for your recents PRs and contributions!!! Me and @villares always get excited when we see new people using and contributing to processing.py mode <3

What do you think about this issue? I'm not a huge Java expert, but I noticed your PRs mostly touch the Java code, so I'm assuming you have some experience with it. I'd love to hear your thoughts about this issue=)

**Comment by mpsftw** [comment]
Python mode uses Jython to access the processing classes, and Jython is currently stuck at 2.7. It might be possible to switch to something like Jep, but expect it would be an absolutely massive undertaking. It's an intimidating thought. I'm not super familiar with the code base here yet, though.

Jep looks nice because it starts a python interpreter from the JVM, which is similar to how Jython is being used. There would still have to be a ton of rewrites and probably some architectural changes. If this is something people really really really want I can dig into it a bit deeper. I wouldn't expect anything to happen quickly, though.

One of the cooler things about Jep is that is uses the good old, run of the mill CPython. That would open up a lot of possibilities. I've never used Jep, so I can't vouch for it working at all, but it's a fantastic thought.

**Comment by villares** [comment]
Another path you might want to consider is instatiating `PApplet` by way of [PyJNIus](https://github.com/kivy/pyjnius), I'm not sure what the implications would be, but it's also a CPython path...

**Comment by jeremydouglass** [comment]
-  Java process:
    - Jep
    - JyNI
    - Jython
-  Python process:
    - JPype
    - PyJNIus
    - Py4J
-  Either / both:
    - jpy

**Comment by mpsftw** [comment]
I think it's doable:

![image](https://user-images.githubusercontent.com/17804292/82848021-05b25b00-9eb7-11ea-9f01-49bd07874d93.png)

**Comment by jeremydouglass** [comment]
Interesting!!!

Currently there is:

- Processing 2 on JVM via Jython  (processing.py)
- Processing 3 native (p5py)
- Processing 3 on JavaScript via Transcrypt (pyp5js)

This would be

-  Processing 3 on JVM via Jep

Would rearchitecting on Jep for Python 3 be such a dramatic change that it would essentially be a separate project?

**Comment by mpsftw** [comment]
That's hard to answer right now. 

I think it should be doable as an addon or something to processing.py. It's not quite a drop in replacement, but it's similar enough to reuse some things. I do worry about backwards compatibility.  It might be possible to swap in Jep and add something like a usePython2() command or something.

I figured I'd get it running as an extension to PApplet - like PAppletJythonDriver - and then figure out what to do with it. Honestly, I'd probably just come back here and ask y'all what you'd like to see. If all goes well, I think I'll be able to have a way of running it from the cli so you can do things like pdb.set_trace() and whatnot.

**Comment by mpsftw** [comment]
Python debugging is working as is, so as long as I can keep a cli version it'll be available.

```
$ java ... pycessing.JepApplet ./test.py
--Return--
> <string>(18)draw()->None
(Pdb) w
  <string>(1)<module>()
> <string>(18)draw()->None
(Pdb) 
```

**Comment by jeremydouglass** [comment]
Well, that would be quite a triumph!

Jep supporting a python syntax Processing that could combine Processing's Java library ecosystem with the CPython ecosystem (numpy, scipy, pandas, tensorflow, matplotlib)... thiswould make a huge array of things possible that haven't been so far. To me, this aspect -- combining peasycam with numpy, for example --  is far more interesting than just python 3 syntax per se.

**Comment by mpsftw** [comment]
Yeah, it feels pretty promising at this point. I don't want to get ahead of myself, though.

![image](https://user-images.githubusercontent.com/17804292/82855052-d825db80-9ecf-11ea-9972-6638ac7b2bf8.png)

**Comment by berinhard** [comment]
Wow! These are very exciting news! Keep on with your explorations @mpsftw!!!!! =) =) =)

**Comment by hx2A** [comment]
Greetings-

I have built a new Python version of Processing and am looking for feedback. This isn't ready to share with the world, but the present functionality does work well. I'm hoping some people who are familiar with Processing and Python can give it a try. This thread seems like a good place to find people who are interested. :)

py5 uses jpype and requires Python 3.8. It supports all of Processing's functionality and renderers. I added new features to provide integration with the Python ecosystem. There's also support for Jupyter notebooks.

The documentation website is a work in progress:

http://py5.ixora.io/

The reference documentation is solid but the how-tos and tutorials are incomplete. There are special notes for Mac users due to an open jpype issue.

These are the relevant github repos:

https://github.com/hx2A/py5
https://github.com/hx2A/py5generator

Any questions, please ask!

**Comment by jeremydouglass** [comment]
Hi @hx2A -- thank you for sharing this. I would be interested in asking questions and giving feedback -- where is the repo for the docs site? I found the Reference materials in py5generator, but couldn't find it the actual docs site, e.g. the tutorials et cetera.

**Comment by hx2A** [comment]
> Hi @hx2A -- thank you for sharing this. I would be interested in asking questions and giving feedback -- where is the repo for the docs site? I found the Reference materials in py5generator, but couldn't find it the actual docs site, e.g. the tutorials et cetera.

Hello, @jeremydouglass , I would be happy to hear your feedback and answer any of your questions. Please join us in the py5generator repo discussions: https://github.com/hx2A/py5generator/discussions

Much of the available documentation is here:

https://py5.ixora.io/

The available tutorials are in the tutorials section: https://py5.ixora.io/tutorials/

The website's repo is https://github.com/hx2A/py5website, but that just has the un-rendered pages from the website. The documentation website is very much a work in progress.

Recently I started working on this: 

https://github.com/hx2A/py5examples

You can run now run py5 through mybinder.

I know the tutorials and how-tos are currently a bit weak. The documentation is a work in progress. Right now I'm trying to get the next release out the door before cc fest this weekend. When things calm down a bit I'll get back to working on more documentation.
